app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

security_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }

user_register:
    path:     /register/
    defaults: { _controller: AppBundle:Security:register }

vuejs_fallback:
    defaults:  { _controller: AppBundle:Default:index }
    path:   /{req}
    requirements:
        req: .*
    defaults:
        req: null
