# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        main:
            anonymous:  true
            provider:   main
            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path: /logout

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:

        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%httpProtocol%' }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%httpProtocol%' }
        - { path: ^/admin/, role: ROLE_ADMIN, requires_channel: '%httpProtocol%' }

